apiVersion: v1
kind: ConfigMap
metadata:
  name: api-requester-config
  namespace: zerotesting
data:
  config.yaml: |
    targets:
      - name: firstClients
        service: zerotesting-lightpush-client
        name_template: "^client-0-(1[0-2]|[0-9])$"
        stateful_set: "client-0"

      - name: jswakuClients
        service: zerotesting-lightpush-client
        stateful_set: "client-0"
        port: 8080

      - name: nwakuClients
        service: zerotesting-lightpush-client
        stateful_set: "client-0"
        port: 8645

      # Example target for gossip priority queue testing
      - name: nimp2pNodes
        service: nimp2p-service
        stateful_set: "nimp2p"
        port: 8645

      - name: nimp2pSlowNodes
        service: nimp2p-service
        stateful_set: "nimp2p-slow"
        port: 8645


    endpoints:
      - name: set-debug
        headers: {"accept": "text/plain"}
        params: {"logLevel": "DEBUG"}
        url: "http://{node}/admin/v1/log-level/DEBUG"
        type: "POST"
        paged: False

      - name: lightpush-publish-static-sharding
        url: "http://{node}:{port}/lightpush/v3/message"
        headers: {"Content-Type": "application/json"}
        params: {"pubsubTopic": "/waku/2/rs/2/0",   "message": {"contentTopic": "/test/1/cross-network/proto", "payload": "W1EsIDIsIDNd"}}
        type: "POST"
        paged: False

      - name: lightpush-publish-auto-sharding
        url: "http://{node}:{port}/lightpush/v3/message"
        headers: {"Content-Type": "application/json"}
        params: { "pubsubTopic":"",   "message": {"contentTopic": "/test/1/cross-network/proto", "payload" : "W1EsIDIsIDNd"}}
        type: "POST"
        paged: False

      # Gossip publish endpoint for nim-libp2p testing
      - name: gossip-publish
        url: "http://{node}:{port}/publish"
        headers: {"Content-Type": "application/json"}
        params: {"topic": "test", "msgSize": 1024, "version": 1}
        type: "POST"
        paged: False


    requests:
      - name: publish-request
        endpoint: lightpush-publish-static-sharding
        retries: 0
        retry_delay: 0.3

      - name: gossip-medium
        endpoint: gossip-publish
        retries: 0
        retry_delay: 0

    actions:
      - name: publish-to-clients-random
        requests: ["publish-request"]
        targets: ["nwakuClients"]
        pod_start_index: 0
        pod_count: 91
        order: ascending
        loop_order: foreach_request_target_each_pod

      # Load test: priority-queues test 2 msg/s per node, 1200 messages per node (10 minutes test duration)
      - name: gossip-medium-overflow
        requests: ["gossip-medium"]
        targets: ["nimp2pNodes"]
        pod_count: "all"
        order: ascending
        loop_order: foreach_pod_make_all_requests
        load_test:
          enabled: true
          rate_per_pod: 2
          messages_per_pod: 1200