import base64
import os
import urllib
from typing import Annotated, Awaitable, Callable, Union

from fastapi import APIRouter, Depends, Request
from pydantic import BaseModel, Field, NonNegativeInt

from common import call_endpoint, get_pod_infos
from configs import ConfigEndpoint
from routers.deps import (
    TargetConfig,
    TargetName,
    endpoint_error_handler,
    unwrap_arg,
)
from schemas import NotFoundError, TargetPodInfo
from utils import redact_keys, setup_logger

logger = setup_logger(__file__)


def get_endpoint_relay_v1(
    content_topic: str,
    cluster_id: NonNegativeInt,
    port: NonNegativeInt,
    msg_size_kbytes: NonNegativeInt,
    node_info: TargetPodInfo,
) -> ConfigEndpoint:
    node_shard = node_info.pod_name.split("-")[1]
    topic = f"/waku/2/rs/{cluster_id}/{node_shard}"
    encoded_topic = urllib.parse.quote(topic, safe="")
    url = f"http://{{node}}:{port}/relay/v1/messages/{encoded_topic}"

    payload = base64.b64encode(os.urandom(msg_size_kbytes * 1000)).decode("ascii").rstrip("=")
    headers = {"Content-Type": "application/json"}
    body = {"payload": payload, "contentTopic": content_topic, "version": 1}

    return ConfigEndpoint(
        name="dummy",
        paged=False,
        type="POST",
        url=url,
        headers=headers,
        params=body,
    )


class WakuRequestData(BaseModel):
    target: Annotated[Union[TargetName, TargetConfig], Field(discriminator="kind")]
    content_topic: str
    cluster_id: int
    port: NonNegativeInt
    msg_size_kbytes: NonNegativeInt


def create_router(get_config: Callable[[], Awaitable[dict]]) -> APIRouter:
    router = APIRouter()

    @router.post("/waku/relay")
    @endpoint_error_handler
    async def waku(
        request: Request,
        data: WakuRequestData,
        config=Depends(get_config),
    ):
        target = unwrap_arg(data.target, "targets", config)

        try:
            pod_info = next(iter(get_pod_infos([target], namespace=request.app.state.namespace)))
        except StopIteration as e:
            raise NotFoundError(f"Target not found. Target: {target}") from e

        endpoint = get_endpoint_relay_v1(
            content_topic=data.content_topic,
            cluster_id=data.cluster_id,
            port=data.port,
            msg_size_kbytes=data.msg_size_kbytes,
            node_info=pod_info,
        )
        result = call_endpoint(endpoint, pod_info)
        # Remove values for "payload", since it is a large amount of generated bytes.
        result = redact_keys(result, keys_to_redact=("payload",))
        configEndpoint = result["request"]["configEndpoint"]
        configEndpoint.params = redact_keys(configEndpoint.params, keys_to_redact=("payload",))
        return result

    return router
